### PR TITLE
CI: improvments

### PR DESCRIPTION
**Pull request by ljubon**
- Optimise matrix jobs and used environments
- update runners `ubuntu-20.04` -> `ubuntu-24.04`
- add `Setup packer` to maintain `packer` version up to date

### CODE REVIEW

**Comment by pavlovic-ivan** [comment]
closed accidentally

**Comment by pavlovic-ivan** [comment]
Parquetsharp has moved to Github hosted runners of arm64 arch, so we can remove Parquetsharp from implementation and keep only ILGPU

**Comment by ljubon** [comment]
> Parquetsharp has moved to Github hosted runners of arm64 arch, so we can remove Parquetsharp from implementation and keep only ILGPU

`Parquetsharp` removed 👍

**Review by pavlovic-ivan — APPROVED** [review]
LGTM. Thanks @ljubon! 🚀

**Pull request merged**
